version: '3.7'

services:
 knar_app:
  env_file: .env
  build:
   args:
    user: ${USER}
    uid: ${UID}
   context: ./
   dockerfile: Dockerfile
  image: knar
  container_name: knar-app
  restart: unless-stopped
  working_dir: /usr/share/nginx/html
  volumes:
    - ${WORK_DIR_SRC}:/usr/share/nginx/html
  networks:
    - knar

 knar_db:
  image: mariadb
  container_name: knar-db
  restart: unless-stopped
  environment:
    MYSQL_DATABASE: knardb
    MYSQL_ROOT_PASSWORD: 123123
    MYSQL_PASSWORD: 123123
    MYSQL_USER: root
  ports: 
  - "3399:3306"    
  volumes:
  - knardata:/var/lib/mysq
  networks:
  - knar

 nginx_knar:
  image: nginx
  env_file: .env
  volumes:
  - ${WORK_DIR_SRC}:/usr/share/nginx/html
  - ${WORK_DIR}:/etc/nginx/conf.d
  ports:
  -  "8999:80"
  networks:
  - knar

networks:
  knar:
    driver: bridge

volumes:
 knardata:
   name: knardata
   external: true
